spring:
  application:
    name: easy-invite
  profiles:
    active: dev
  google:
    client-id: 370415873876-ocdod6anb1833eb8q7n45dt49bj0d9pe.apps.googleusercontent.com

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://pc-2-vila:5433/easy_invite
    username: user
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  upload-dir: "\\\\PC-2-VILA\\invites$\\images"

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  upload-dir: ${IMAGE_FOLDER}