spring.application.name=easy-invite
spring.profiles.active=dev
spring.google.client-id=370415873876-ocdod6anb1833eb8q7n45dt49bj0d9pe.apps.googleusercontent.com

security.jwt.expiration-ms=604800000
security.cookie.name=AUTH_TOKEN